services:
  app:
    image: node:22.23.2-bookworm-slim
    ports:
      - "4321:4321"
    working_dir: /app
    command: sh -c "npm install --global pnpm@11.19.0 && pnpm install --frozen-lockfile && pnpm dev --host 0.0.0.0"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
