name: CI

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_call:

jobs:
  build:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit:security
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm build
      - run: pnpm verify:migration
